### ISSUE TITLE
Response fails its own type validation

### ISSUE THREAD

**Issue by emnC5117** [maxio-com/ab-typescript-sdk#71]
We are working on converting our API over to use the new advanced-billing-sdk. We have run into an issue for the subscriptionsController.readSubscription and subscriptionGroupsController.addSubscriptionToGroup methods where the method response fails its own type validation.

As you can see in this image, it expects an optional string, the actual returned value is null and it thinks the return type is object.

![image](https://github.com/maxio-com/ab-typescript-sdk/assets/162641652/8b2a6f30-7233-44d9-beb9-ccde48fbd11b)

We suspect this issue probably affects more methods than just these two. With the readSubscription method, there seemed to be a correlation between the user being canceled and the validation failures (presumably because it causes some values to be null or undefined). The root issue seems like the type validation just isn't properly handling for values that can be null.

Please help to resolve this quickly, as the sdk is kind of useless to us if it will arbitrarily refuse to return information back to our API.

**Comment by Noskilo** [comment]
This seems to happen for the `InvoicesController` as well.

**Comment by michalpierog** [comment]
Sorry for the delay, we are investigating this issue. We will let you know about targeted date for the fix.

**Comment by michalpierog** [comment]
@Noskilo Do you have an error message for the InvoicesController?

**Comment by RBornost** [comment]
I have found a similar or possibly the same error
using SDK version "@maxio-com/advanced-billing-sdk": "^8.0.0"

I removed subscription data due to PII but the error is because the response validation thinks snap_day should be a number | "end" which as i recall it used to be. Now it is 
snapDay | string | null | undefined Nullable A day of month that subscription will be processed on. Can be 1 up to 28 or 'end'.

{
  "severity": "error",
  "time": "2026-04-02T03:52:45.487Z",
  "pid": 28,
  "hostname": "product-user-events-product-user-events-prod2-68978b8c79-d6rfh",
  "tags": [
    "product-user-events@0.0.0-development",
    "/package/lib/services/customer-subscriptions.js"
  ],
  "payload": {
    "oops": {
      "type": "ResponseValidationError",
      "message": "The response did not match the response schema.\n\nCould not match against any acceptable type.\n\nGiven value: \"17\"\nType: 'string'\nExpected type: 'Optional<Nullable<OneOf<number | Enum<\"end\">>>>'\nPath: 2 › subscription › snap_day",
      "stack": "Error: The response did not match the response schema.\n\nCould not match against any acceptable type.\n\nGiven value: \"17\"\nType: 'string'\nExpected type: 'Optional<Nullable<OneOf<number | Enum<\"end\">>>>'\nPath: 2 › subscription › snap_day\n    at new ResponseValidationError (/package/node_modules/@apimatic/core/lib/errors/responseValidationError.js:22:24)\n    at resInvalidErr (/package/node_modules/@apimatic/core/lib/http/requestBuilder.js:751:16)\n    at /package/node_modules/@apimatic/core/lib/http/requestBuilder.js:753:68\n    at validateJson (/package/node_modules/@apimatic/core/lib/http/requestBuilder.js:758:15)\n    at parseJsonResult (/package/node_modules/@apimatic/core/lib/http/requestBuilder.js:753:12)\n    at DefaultRequestBuilder.<anonymous> (/package/node_modules/@apimatic/core/lib/http/requestBuilder.js:344:104)\n    at step (/package/node_modules/tslib/tslib.js:196:27)\n    at Object.next (/package/node_modules/tslib/tslib.js:177:57)\n    at fulfilled (/package/node_modules/tslib/tslib.js:167:62)\n    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)",
      "request": {
        "method": "GET",
        "url": "https://symbolik.chargify.com/customers/57601724/subscriptions.json",
      },
      "statusCode": 200,
      "headers": {
        "date": "Thu, 02 Apr 2026 03:52:45 GMT",

      },
      "errors": [
        {
          "value": "17",
          "type": "Optional<Nullable<OneOf<number | Enum<\"end\">>>>",
          "branch": [

          ],
          "path": [
            2,
            "subscription",
            "snap_day"
          ],
          "message": "Could not match against any acceptable type.\n\nGiven value: \"17\"\nType: 'string'\nExpected type: 'Optional<Nullable<OneOf<number | Enum<\"end\">>>>'\nPath: 2 › subscription › snap_day"
        }
      ]
    },
    "userId": "cl6wnuadt01xy0spkedgv3yo2"
  },
  "message": "RAW ERROR Error getting subscriptions for customer."
}
